"""add tag to table products

Revision ID: 7fb04a73e1e1
Revises: ba7da68faeae
Create Date: 2026-07-10 17:05:22.157453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb04a73e1e1'
down_revision: Union[str, Sequence[str], None] = 'ba7da68faeae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tag', sa.Enum('bebidas', 'hamburgueres', 'porcoes', name='producttag'), nullable=False))
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('address',
                existing_type=sa.VARCHAR(),
                nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.alter_column('address',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
    op.drop_column('products', 'tag')
    # ### end Alembic commands ###
