"""modify order and product tables

Revision ID: ba7da68faeae
Revises: 43c5dc88b5c5
Create Date: 2026-07-01 17:37:38.370376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7da68faeae'
down_revision: Union[str, Sequence[str], None] = '43c5dc88b5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('final_amount', sa.Numeric(), nullable=False))
    op.add_column('orders', sa.Column('estimated_ready_at', sa.DateTime(), nullable=False))
    op.add_column('products', sa.Column('price', sa.Numeric(), nullable=False))
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('products', 'price')
    op.drop_column('orders', 'estimated_ready_at')
    op.drop_column('orders', 'final_amount')
    # ### end Alembic commands ###
